image_width: 376
image_height: 240
max_px_speed: 70
max_speed: 9
max_acceleration: 2.77
speed_noise: 1.5
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [260.923833, 0.000000, 173.849864, 0.000000, 261.085438, 108.174887, 0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.465186, 0.183808, 0.001438, -0.001623, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000]
projection_matrix:
  rows: 3
  cols: 4
  data: [192.105453, 0.000000, 169.922855, 0.000000, 0.000000, 229.518890, 104.794880, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]
